name: domjudge

# The following variables are set in the ./.env file
# Variables for versioning the images:
#   - DOMJUDGE_VERSION
#   - MARIADB_VERSION
#   - CADDY_VERSION
#   - MARIADB_ROLLING_BACKUP_VERSION
# Variables for backup service:
#   - BACKUP_CRON_SCHEDULE (e.g., "0 2 * * *")
#   - MAX_NUM_BACKUPS_TO_KEEP (e.g. 20) 
#   - CREATE_CHECKSUM (eg. "true"} 
#   - TABLES_TO_EXCLUDE_IN_CHECKSUM # comma separated list of tables to exclude from checksum calculation, e.g. "table1,table2"
#   - REMOVE_CHECKSUM_EQUIV_PREVIOUS_BACKUP  # if true, will discard a backup if its checksum is the same as the previous backup  
#     # note:REMOVE_CHECKSUM_EQUIV_PREVIOUS_BACKUP implies CREATE_CHECKSUMS=true

networks:
  domjudge:
    name: domjudge
  reverseproxy:
    name: caddy_reverseproxy

services:
  caddy:
    image: caddy:${CADDY_VERSION}
    container_name: caddy
    restart: unless-stopped
    ports:
      ## production:
      #- "80:80"
      #- "443:443"
      ## development/testing:
      - "1443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - reverseproxy
    profiles:
      - auto-https

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    networks:
      - domjudge
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    command: --max-connections=1000 --max-allowed-packet=1G
    volumes:
      - ./data/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-prootpw"]
      interval: 10s
      timeout: 5s
      retries: 5      

  domserver:
    image: domjudge/domserver:${DOMJUDGE_VERSION}
    container_name: domserver
    hostname: domserver
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/passwords:/passwords
      - ./start.ro:/scripts/start.ro
    networks:
      - domjudge
      - reverseproxy
    ports:
      ## for development/testing:
      - 127.0.0.1:1080:80
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - CONTAINER_TIMEZONE=Europe/Amsterdam
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    healthcheck:
      test: ["CMD", "/scripts/bin/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 50    

  judgehost-0:
    image: harcokuppens/judgehost-extra-languages:${DOMJUDGE_VERSION}
    container_name: judgehost-0
    hostname: judgedaemon-0
    restart: unless-stopped
    privileged: true
    networks:
      - domjudge
    depends_on:
      domserver:
        condition: service_healthy
    environment:
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD_FILE=/passwords/judgehost.pw
      - SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./data/passwords:/passwords:ro


  judgehost-1:
    image: harcokuppens/judgehost-extra-languages:${DOMJUDGE_VERSION}
    container_name: judgehost-1
    hostname: judgedaemon-1
    restart: unless-stopped
    privileged: true
    networks:
      - domjudge
    depends_on:
      domserver:
        condition: service_healthy
    environment:
      - DAEMON_ID=1
      - JUDGEDAEMON_PASSWORD_FILE=/passwords/judgehost.pw
      - SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./data/passwords:/passwords:ro

  backup:
    image: harcokuppens/mariadb-rolling-backup:${BACKUP_VERSION}
    container_name: mariadb-rolling-backup
    hostname: backup
    restart: unless-stopped
    networks:
      - domjudge
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      # These variables are read by the backup script and the crontab
      # note: MYSQL_HOST=mariadb is fixed in backup script for now
      - CONTAINER_TIMEZONE=Europe/Amsterdam
      - MYSQL_HOST=mariadb  
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=domjudge  
      # below variables can be set in .env file or will take the default values shown here
      # the sevariables are used to generate the crontab entry for the mariadb-rolling-backup command 
      - CRON_SCHEDULE=${BACKUP_CRON_SCHEDULE}
      - MAX_NUM_BACKUPS_TO_KEEP=${MAX_NUM_BACKUPS_TO_KEEP} # -k VALUE option 
      - CREATE_CHECKSUMS=${CREATE_CHECKSUMS} # -c --checksum option (if true )
      # comma separated list of tables to exclude from checksum calculation, e.g. "table1,table2"
      - TABLES_TO_EXCLUDE_IN_CHECKSUM=${TABLES_TO_EXCLUDE_IN_CHECKSUM} # -e --exclude-tables-in-checksum option
      # if true, will discard a backup if its checksum is the same as the previous backup  
      - REMOVE_CHECKSUM_EQUIV_PREVIOUS_BACKUP=${REMOVE_CHECKSUM_EQUIV_PREVIOUS_BACKUP} # -r --remove-eq-prev option
      # note:REMOVE_CHECKSUM_EQUIV_PREVIOUS_BACKUP implies CREATE_CHECKSUMS=true
      # in the container the backups are always at /backups; but you can set a different location for the logfile
      - LOGFILE=/backups/backup.log
    volumes:
      # location to store backups on the host; in the container the backups are at /backups
      - ./data/backups:/backups
