name: domjudge

# The following variables are set in the ./.env file
#   - DOMJUDGE_VERSION
#   - MARIADB_VERSION

networks:
  domjudge:
    name: domjudge
  reverseproxy:
    name: caddy_reverseproxy

services:
  caddy:
    image: caddy:2.6-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      ## production:
      #- "80:80"
      #- "443:443"
      ## development/testing:
      - "1443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - reverseproxy
    profiles:
      - auto-https

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    networks:
      - domjudge
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    command: --max-connections=1000 --max-allowed-packet=1G
    volumes:
      - ./data/mariadb:/var/lib/mysql

  domserver:
    image: domjudge/domserver:${DOMJUDGE_VERSION}
    container_name: domserver
    hostname: domserver
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/passwords:/passwords
      - ./start.ro:/scripts/start.ro
    networks:
      - domjudge
      - reverseproxy
    ports:
      ## for development/testing:
      - 127.0.0.1:1080:80
    depends_on:
      - mariadb
    environment:
      - CONTAINER_TIMEZONE=Europe/Amsterdam
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge

  judgehost-0:
    image: domjudge/judgehost:${DOMJUDGE_VERSION}
    container_name: judgehost-0
    hostname: judgedaemon-0
    restart: unless-stopped
    privileged: true
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD_FILE=/passwords/judgehost.pw
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/passwords:/passwords:ro
      - ./install-extra-languages/install-languages:/chroot/domjudge/bin/install-languages:ro
      - ./install-extra-languages/wrapped-start.sh:/scripts/wrapped-start.sh:ro
    command: /scripts/wrapped-start.sh

  judgehost-1:
    image: domjudge/judgehost:${DOMJUDGE_VERSION}
    container_name: judgehost-1
    hostname: judgedaemon-1
    restart: unless-stopped
    privileged: true
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=1
      - JUDGEDAEMON_PASSWORD_FILE=/passwords/judgehost.pw
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/passwords:/passwords:ro
      - ./install-extra-languages/install-languages:/chroot/domjudge/bin/install-languages:ro
      - ./install-extra-languages/wrapped-start.sh:/scripts/wrapped-start.sh:ro
    command: /scripts/wrapped-start.sh
