name: domjudge

# The following variables are set in the ./.env file
#   - DOMJUDGE_VERSION
#   - MARIADB_VERSION

networks:
  domjudge:
    name: domjudge
  reverseproxy:
    name: caddy_reverseproxy

services:
  caddy:
    image: caddy:${CADDY_VERSION}
    container_name: caddy
    restart: unless-stopped
    ports:
      ## production:
      #- "80:80"
      #- "443:443"
      ## development/testing:
      - "1443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - reverseproxy
    profiles:
      - auto-https

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    networks:
      - domjudge
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    command: --max-connections=1000 --max-allowed-packet=1G
    volumes:
      - ./data/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-prootpw"]
      interval: 10s
      timeout: 5s
      retries: 5      

  domserver:
    image: domjudge/domserver:${DOMJUDGE_VERSION}
    container_name: domserver
    hostname: domserver
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/passwords:/passwords
      - ./start.ro:/scripts/start.ro
    networks:
      - domjudge
      - reverseproxy
    ports:
      ## for development/testing:
      - 127.0.0.1:1080:80
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - CONTAINER_TIMEZONE=Europe/Amsterdam
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    healthcheck:
      test: ["CMD", "/scripts/bin/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 50    

  judgehost-0:
    image: ghcr.io/harcokuppens/domjudgedockercompose/judgehost-extra-languages:${DOMJUDGE_VERSION}
    container_name: judgehost-0
    hostname: judgedaemon-0
    restart: unless-stopped
    privileged: true
    networks:
      - domjudge
    depends_on:
      domserver:
        condition: service_healthy
    environment:
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD_FILE=/passwords/judgehost.pw
      - SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./data/passwords:/passwords:ro


  judgehost-1:
    image: ghcr.io/harcokuppens/domjudgedockercompose/judgehost-extra-languages:${DOMJUDGE_VERSION}
    container_name: judgehost-1
    hostname: judgedaemon-1
    restart: unless-stopped
    privileged: true
    networks:
      - domjudge
    depends_on:
      domserver:
        condition: service_healthy
    environment:
      - DAEMON_ID=1
      - JUDGEDAEMON_PASSWORD_FILE=/passwords/judgehost.pw
      - SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./data/passwords:/passwords:ro

