#!/bin/sh

# this script installs extra languages withing the chroot environment of the judgehost
# this script is run within the chroot environment of the judgehost
# commands in this script must run non-interactive
# note: the installed languages must manually be enabled in the domserver. However
#       this only needs to be done once, because these settings are persistently stored
#       in the mariadb domjudge database on disk.

# install rustc
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --no-install-suggests -y rustc kotlin
